Fix skipping signature section when it is larger than previously seen
fw2elf.py failed with
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/iwlwifi-ty-a0-gf-a0-78.ucode

    Skipping aaaabbbb..aaaabbbf: separator (Regular ucode)
    Loading 00000000..00000678: 0x678=1656 bytes of Regular ucode
    Traceback (most recent call last):
      File "./fw2elf.py", line 341, in <module>
        craft_elf(args.ucode, args.out)
      File "./fw2elf.py", line 320, in craft_elf
        regular_segments.add_segment(addr, section.data)
      File "./fw2elf.py", line 29, in add_segment
        raise ValueError(f"Refusing to add segment {addr:#x}..{addr_end:#x} because it overlaps with {seg_addr:#x}..{seg_addr_end:#x}")
    ValueError: Refusing to add segment 0x0..0x678 because it overlaps with 0x0..0x8000

Use a larger bound to detect signature sections to skip this section
appropriately.